import DS from 'ember-data';

var attr = DS.attr,
    //hasMany = DS.hasMany,
    belongsTo = DS.belongsTo;

var SeasonStat = DS.Model.extend({
    player: belongsTo('player',{async:true}),
    season: attr(),             // which season, currently year as number
    numPlays: attr(),           // total num plays in this season
    numGames: attr(),           // total num games in this season
    mainCat1Grade: attr(),      // average grade across all games/plays
    mainCat2Grade: attr(),      // average grade across all games/plays
    mainCat3Grade: attr(),      // average grade across all games/plays
    bonusGrade: attr(),         // average grade across all games/plays
    overallGrade: attr(),       // average grade across all games/plays
    unitImpactGrade: attr()     // average grade across all games/plays
});

SeasonStat.reopenClass({
FIXTURES:
    [
        {
            "id":72,
            "player": 72,
            "season": 2014,
            "numPlays": 440,
            "numGames": 6,
            "bonusGrade": 88,
            "unitImpactGrade": 89,
            "mainCat1Grade": 93,
            "mainCat2Grade": 101,
            "mainCat3Grade": 100,
            "overallGrade": 95
        },
        {
            "id":80,
            "player": 80,
            "season": 2014,
            "numPlays": 307,
            "numGames": 6,
            "bonusGrade": 91,
            "unitImpactGrade": 82,
            "mainCat1Grade": 95,
            "mainCat2Grade": 87,
            "mainCat3Grade": 102,
            "overallGrade": 94
        },
        {
            "id":19,
            "player": 19,
            "season": 2014,
            "numPlays": 320,
            "numGames": 6,
            "bonusGrade": 95,
            "unitImpactGrade": 74,
            "mainCat1Grade": 97,
            "mainCat2Grade": 90,
            "mainCat3Grade": 94,
            "overallGrade": 94
        },
        {
            "id":23,
            "player": 23,
            "season": 2014,
            "numPlays": 231,
            "numGames": 6,
            "bonusGrade": 91,
            "unitImpactGrade": 95,
            "mainCat1Grade": 100,
            "mainCat2Grade": 89,
            "mainCat3Grade": 91,
            "overallGrade": 93
        },
        {
            "id":14,
            "player": 14,
            "season": 2014,
            "numPlays": 302,
            "numGames": 6,
            "bonusGrade": 92,
            "unitImpactGrade": 84,
            "mainCat1Grade": 95,
            "mainCat2Grade": 93,
            "mainCat3Grade": 89,
            "overallGrade": 93
        },
        {
            "id":37,
            "player": 37,
            "season": 2014,
            "numPlays": 362,
            "numGames": 6,
            "bonusGrade": 90,
            "unitImpactGrade": 87,
            "mainCat1Grade": 90,
            "mainCat2Grade": 93,
            "mainCat3Grade": 96,
            "overallGrade": 93
        },
        {
            "id":4,
            "player": 4,
            "season": 2014,
            "numPlays": 314,
            "numGames": 6,
            "bonusGrade": 85,
            "unitImpactGrade": 77,
            "mainCat1Grade": 100,
            "mainCat2Grade": 93,
            "mainCat3Grade": 93,
            "overallGrade": 93
        },
        {
            "id":12,
            "player": 12,
            "season": 2014,
            "numPlays": 360,
            "numGames": 6,
            "bonusGrade": 89,
            "unitImpactGrade": 85,
            "mainCat1Grade": 92,
            "mainCat2Grade": 93,
            "mainCat3Grade": 91,
            "overallGrade": 92
        },
        {
            "id":45,
            "player": 45,
            "season": 2014,
            "numPlays": 280,
            "numGames": 6,
            "bonusGrade": 92,
            "unitImpactGrade": 91,
            "mainCat1Grade": 94,
            "mainCat2Grade": 94,
            "mainCat3Grade": 87,
            "overallGrade": 92
        },
        {
            "id":42,
            "player": 42,
            "season": 2014,
            "numPlays": 308,
            "numGames": 6,
            "bonusGrade": 89,
            "unitImpactGrade": 83,
            "mainCat1Grade": 91,
            "mainCat2Grade": 97,
            "mainCat3Grade": 90,
            "overallGrade": 92
        },
        {
            "id":41,
            "player": 41,
            "season": 2014,
            "numPlays": 252,
            "numGames": 6,
            "bonusGrade": 93,
            "unitImpactGrade": 86,
            "mainCat1Grade": 94,
            "mainCat2Grade": 90,
            "mainCat3Grade": 90,
            "overallGrade": 92
        },
        {
            "id":39,
            "player": 39,
            "season": 2014,
            "numPlays": 225,
            "numGames": 6,
            "bonusGrade": 90,
            "unitImpactGrade": 74,
            "mainCat1Grade": 96,
            "mainCat2Grade": 92,
            "mainCat3Grade": 90,
            "overallGrade": 92
        },
        {
            "id":88,
            "player": 88,
            "season": 2014,
            "numPlays": 309,
            "numGames": 6,
            "bonusGrade": 80,
            "unitImpactGrade": 78,
            "mainCat1Grade": 99,
            "mainCat2Grade": 93,
            "mainCat3Grade": 94,
            "overallGrade": 92
        },
        {
            "id":28,
            "player": 28,
            "season": 2014,
            "numPlays": 286,
            "numGames": 6,
            "bonusGrade": 82,
            "unitImpactGrade": 82,
            "mainCat1Grade": 93,
            "mainCat2Grade": 95,
            "mainCat3Grade": 97,
            "overallGrade": 92
        },
        {
            "id":79,
            "player": 79,
            "season": 2014,
            "numPlays": 347,
            "numGames": 6,
            "bonusGrade": 85,
            "unitImpactGrade": 82,
            "mainCat1Grade": 91,
            "mainCat2Grade": 96,
            "mainCat3Grade": 93,
            "overallGrade": 92
        },
        {
            "id":2,
            "player": 2,
            "season": 2014,
            "numPlays": 261,
            "numGames": 6,
            "bonusGrade": 88,
            "unitImpactGrade": 82,
            "mainCat1Grade": 98,
            "mainCat2Grade": 92,
            "mainCat3Grade": 91,
            "overallGrade": 92
        },
        {
            "id":67,
            "player": 67,
            "season": 2014,
            "numPlays": 297,
            "numGames": 6,
            "bonusGrade": 86,
            "unitImpactGrade": 98,
            "mainCat1Grade": 91,
            "mainCat2Grade": 92,
            "mainCat3Grade": 93,
            "overallGrade": 91
        },
        {
            "id":54,
            "player": 54,
            "season": 2014,
            "numPlays": 279,
            "numGames": 6,
            "bonusGrade": 81,
            "unitImpactGrade": 88,
            "mainCat1Grade": 95,
            "mainCat2Grade": 90,
            "mainCat3Grade": 95,
            "overallGrade": 91
        },
        {
            "id":97,
            "player": 97,
            "season": 2014,
            "numPlays": 227,
            "numGames": 6,
            "bonusGrade": 87,
            "unitImpactGrade": 78,
            "mainCat1Grade": 95,
            "mainCat2Grade": 90,
            "mainCat3Grade": 92,
            "overallGrade": 91
        },
        {
            "id":89,
            "player": 89,
            "season": 2014,
            "numPlays": 237,
            "numGames": 6,
            "bonusGrade": 81,
            "unitImpactGrade": 89,
            "mainCat1Grade": 95,
            "mainCat2Grade": 96,
            "mainCat3Grade": 93,
            "overallGrade": 91
        },
        {
            "id":77,
            "player": 77,
            "season": 2014,
            "numPlays": 276,
            "numGames": 6,
            "bonusGrade": 85,
            "unitImpactGrade": 78,
            "mainCat1Grade": 94,
            "mainCat2Grade": 95,
            "mainCat3Grade": 90,
            "overallGrade": 91
        },
        {
            "id":81,
            "player": 81,
            "season": 2014,
            "numPlays": 278,
            "numGames": 6,
            "bonusGrade": 82,
            "unitImpactGrade": 83,
            "mainCat1Grade": 92,
            "mainCat2Grade": 96,
            "mainCat3Grade": 92,
            "overallGrade": 91
        },
        {
            "id":46,
            "player": 46,
            "season": 2014,
            "numPlays": 334,
            "numGames": 6,
            "bonusGrade": 86,
            "unitImpactGrade": 75,
            "mainCat1Grade": 90,
            "mainCat2Grade": 92,
            "mainCat3Grade": 95,
            "overallGrade": 91
        },
        {
            "id":35,
            "player": 35,
            "season": 2014,
            "numPlays": 258,
            "numGames": 6,
            "bonusGrade": 88,
            "unitImpactGrade": 93,
            "mainCat1Grade": 98,
            "mainCat2Grade": 86,
            "mainCat3Grade": 90,
            "overallGrade": 91
        },
        {
            "id":98,
            "player": 98,
            "season": 2014,
            "numPlays": 384,
            "numGames": 6,
            "bonusGrade": 88,
            "unitImpactGrade": 89,
            "mainCat1Grade": 96,
            "mainCat2Grade": 88,
            "mainCat3Grade": 93,
            "overallGrade": 91
        },
        {
            "id":27,
            "player": 27,
            "season": 2014,
            "numPlays": 234,
            "numGames": 6,
            "bonusGrade": 88,
            "unitImpactGrade": 81,
            "mainCat1Grade": 85,
            "mainCat2Grade": 98,
            "mainCat3Grade": 94,
            "overallGrade": 91
        },
        {
            "id":94,
            "player": 94,
            "season": 2014,
            "numPlays": 155,
            "numGames": 6,
            "bonusGrade": 82,
            "unitImpactGrade": 86,
            "mainCat1Grade": 87,
            "mainCat2Grade": 96,
            "mainCat3Grade": 94,
            "overallGrade": 90
        },
        {
            "id":91,
            "player": 91,
            "season": 2014,
            "numPlays": 280,
            "numGames": 6,
            "bonusGrade": 85,
            "unitImpactGrade": 91,
            "mainCat1Grade": 95,
            "mainCat2Grade": 86,
            "mainCat3Grade": 94,
            "overallGrade": 90
        },
        {
            "id":26,
            "player": 26,
            "season": 2014,
            "numPlays": 327,
            "numGames": 6,
            "bonusGrade": 81,
            "unitImpactGrade": 84,
            "mainCat1Grade": 94,
            "mainCat2Grade": 97,
            "mainCat3Grade": 87,
            "overallGrade": 90
        },
        {
            "id":7,
            "player": 7,
            "season": 2014,
            "numPlays": 291,
            "numGames": 6,
            "bonusGrade": 83,
            "unitImpactGrade": 79,
            "mainCat1Grade": 92,
            "mainCat2Grade": 91,
            "mainCat3Grade": 93,
            "overallGrade": 90
        },
        {
            "id":82,
            "player": 82,
            "season": 2014,
            "numPlays": 296,
            "numGames": 6,
            "bonusGrade": 89,
            "unitImpactGrade": 83,
            "mainCat1Grade": 91,
            "mainCat2Grade": 90,
            "mainCat3Grade": 88,
            "overallGrade": 90
        },
        {
            "id":21,
            "player": 21,
            "season": 2014,
            "numPlays": 382,
            "numGames": 6,
            "bonusGrade": 87,
            "unitImpactGrade": 83,
            "mainCat1Grade": 93,
            "mainCat2Grade": 86,
            "mainCat3Grade": 92,
            "overallGrade": 90
        },
        {
            "id":52,
            "player": 52,
            "season": 2014,
            "numPlays": 398,
            "numGames": 6,
            "bonusGrade": 78,
            "unitImpactGrade": 84,
            "mainCat1Grade": 89,
            "mainCat2Grade": 97,
            "mainCat3Grade": 97,
            "overallGrade": 90
        },
        {
            "id":51,
            "player": 51,
            "season": 2014,
            "numPlays": 210,
            "numGames": 6,
            "bonusGrade": 81,
            "unitImpactGrade": 81,
            "mainCat1Grade": 95,
            "mainCat2Grade": 92,
            "mainCat3Grade": 93,
            "overallGrade": 90
        },
        {
            "id":49,
            "player": 49,
            "season": 2014,
            "numPlays": 259,
            "numGames": 6,
            "bonusGrade": 84,
            "unitImpactGrade": 86,
            "mainCat1Grade": 89,
            "mainCat2Grade": 90,
            "mainCat3Grade": 97,
            "overallGrade": 90
        },
        {
            "id":10,
            "player": 10,
            "season": 2014,
            "numPlays": 251,
            "numGames": 6,
            "bonusGrade": 82,
            "unitImpactGrade": 93,
            "mainCat1Grade": 90,
            "mainCat2Grade": 91,
            "mainCat3Grade": 95,
            "overallGrade": 90
        },
        {
            "id":69,
            "player": 69,
            "season": 2014,
            "numPlays": 325,
            "numGames": 6,
            "bonusGrade": 84,
            "unitImpactGrade": 76,
            "mainCat1Grade": 94,
            "mainCat2Grade": 94,
            "mainCat3Grade": 85,
            "overallGrade": 90
        },
        {
            "id":18,
            "player": 18,
            "season": 2014,
            "numPlays": 271,
            "numGames": 6,
            "bonusGrade": 79,
            "unitImpactGrade": 69,
            "mainCat1Grade": 99,
            "mainCat2Grade": 88,
            "mainCat3Grade": 93,
            "overallGrade": 90
        },
        {
            "id":5,
            "player": 5,
            "season": 2014,
            "numPlays": 282,
            "numGames": 6,
            "bonusGrade": 88,
            "unitImpactGrade": 84,
            "mainCat1Grade": 91,
            "mainCat2Grade": 92,
            "mainCat3Grade": 88,
            "overallGrade": 90
        },
        {
            "id":11,
            "player": 11,
            "season": 2014,
            "numPlays": 268,
            "numGames": 6,
            "bonusGrade": 81,
            "unitImpactGrade": 86,
            "mainCat1Grade": 95,
            "mainCat2Grade": 93,
            "mainCat3Grade": 84,
            "overallGrade": 89
        },
        {
            "id":40,
            "player": 40,
            "season": 2014,
            "numPlays": 206,
            "numGames": 6,
            "bonusGrade": 84,
            "unitImpactGrade": 73,
            "mainCat1Grade": 88,
            "mainCat2Grade": 91,
            "mainCat3Grade": 93,
            "overallGrade": 89
        },
        {
            "id":50,
            "player": 50,
            "season": 2014,
            "numPlays": 302,
            "numGames": 6,
            "bonusGrade": 82,
            "unitImpactGrade": 87,
            "mainCat1Grade": 87,
            "mainCat2Grade": 92,
            "mainCat3Grade": 92,
            "overallGrade": 89
        },
        {
            "id":24,
            "player": 24,
            "season": 2014,
            "numPlays": 378,
            "numGames": 6,
            "bonusGrade": 82,
            "unitImpactGrade": 79,
            "mainCat1Grade": 89,
            "mainCat2Grade": 91,
            "mainCat3Grade": 93,
            "overallGrade": 89
        },
        {
            "id":16,
            "player": 16,
            "season": 2014,
            "numPlays": 253,
            "numGames": 6,
            "bonusGrade": 78,
            "unitImpactGrade": 95,
            "mainCat1Grade": 98,
            "mainCat2Grade": 90,
            "mainCat3Grade": 88,
            "overallGrade": 89
        },
        {
            "id":36,
            "player": 36,
            "season": 2014,
            "numPlays": 309,
            "numGames": 6,
            "bonusGrade": 78,
            "unitImpactGrade": 76,
            "mainCat1Grade": 96,
            "mainCat2Grade": 93,
            "mainCat3Grade": 88,
            "overallGrade": 89
        },
        {
            "id":64,
            "player": 64,
            "season": 2014,
            "numPlays": 300,
            "numGames": 6,
            "bonusGrade": 87,
            "unitImpactGrade": 91,
            "mainCat1Grade": 92,
            "mainCat2Grade": 88,
            "mainCat3Grade": 88,
            "overallGrade": 89
        },
        {
            "id":58,
            "player": 58,
            "season": 2014,
            "numPlays": 297,
            "numGames": 6,
            "bonusGrade": 80,
            "unitImpactGrade": 90,
            "mainCat1Grade": 88,
            "mainCat2Grade": 94,
            "mainCat3Grade": 93,
            "overallGrade": 89
        },
        {
            "id":57,
            "player": 57,
            "season": 2014,
            "numPlays": 259,
            "numGames": 6,
            "bonusGrade": 83,
            "unitImpactGrade": 82,
            "mainCat1Grade": 93,
            "mainCat2Grade": 91,
            "mainCat3Grade": 90,
            "overallGrade": 89
        },
        {
            "id":55,
            "player": 55,
            "season": 2014,
            "numPlays": 305,
            "numGames": 6,
            "bonusGrade": 80,
            "unitImpactGrade": 70,
            "mainCat1Grade": 88,
            "mainCat2Grade": 95,
            "mainCat3Grade": 91,
            "overallGrade": 89
        },
        {
            "id":71,
            "player": 71,
            "season": 2014,
            "numPlays": 330,
            "numGames": 6,
            "bonusGrade": 80,
            "unitImpactGrade": 94,
            "mainCat1Grade": 92,
            "mainCat2Grade": 94,
            "mainCat3Grade": 91,
            "overallGrade": 89
        },
        {
            "id":22,
            "player": 22,
            "season": 2014,
            "numPlays": 324,
            "numGames": 6,
            "bonusGrade": 80,
            "unitImpactGrade": 82,
            "mainCat1Grade": 87,
            "mainCat2Grade": 94,
            "mainCat3Grade": 94,
            "overallGrade": 89
        },
        {
            "id":96,
            "player": 96,
            "season": 2014,
            "numPlays": 229,
            "numGames": 6,
            "bonusGrade": 81,
            "unitImpactGrade": 76,
            "mainCat1Grade": 94,
            "mainCat2Grade": 94,
            "mainCat3Grade": 87,
            "overallGrade": 89
        },
        {
            "id":68,
            "player": 68,
            "season": 2014,
            "numPlays": 297,
            "numGames": 6,
            "bonusGrade": 83,
            "unitImpactGrade": 81,
            "mainCat1Grade": 95,
            "mainCat2Grade": 89,
            "mainCat3Grade": 90,
            "overallGrade": 89
        },
        {
            "id":93,
            "player": 93,
            "season": 2014,
            "numPlays": 197,
            "numGames": 6,
            "bonusGrade": 81,
            "unitImpactGrade": 74,
            "mainCat1Grade": 90,
            "mainCat2Grade": 89,
            "mainCat3Grade": 94,
            "overallGrade": 89
        },
        {
            "id":92,
            "player": 92,
            "season": 2014,
            "numPlays": 301,
            "numGames": 6,
            "bonusGrade": 88,
            "unitImpactGrade": 87,
            "mainCat1Grade": 89,
            "mainCat2Grade": 93,
            "mainCat3Grade": 86,
            "overallGrade": 89
        },
        {
            "id":32,
            "player": 32,
            "season": 2014,
            "numPlays": 284,
            "numGames": 6,
            "bonusGrade": 88,
            "unitImpactGrade": 74,
            "mainCat1Grade": 87,
            "mainCat2Grade": 84,
            "mainCat3Grade": 96,
            "overallGrade": 89
        },
        {
            "id":66,
            "player": 66,
            "season": 2014,
            "numPlays": 323,
            "numGames": 6,
            "bonusGrade": 81,
            "unitImpactGrade": 80,
            "mainCat1Grade": 90,
            "mainCat2Grade": 92,
            "mainCat3Grade": 91,
            "overallGrade": 89
        },
        {
            "id":65,
            "player": 65,
            "season": 2014,
            "numPlays": 256,
            "numGames": 6,
            "bonusGrade": 86,
            "unitImpactGrade": 86,
            "mainCat1Grade": 90,
            "mainCat2Grade": 95,
            "mainCat3Grade": 84,
            "overallGrade": 89
        },
        {
            "id":9,
            "player": 9,
            "season": 2014,
            "numPlays": 237,
            "numGames": 6,
            "bonusGrade": 83,
            "unitImpactGrade": 79,
            "mainCat1Grade": 97,
            "mainCat2Grade": 92,
            "mainCat3Grade": 84,
            "overallGrade": 89
        },
        {
            "id":61,
            "player": 61,
            "season": 2014,
            "numPlays": 335,
            "numGames": 6,
            "bonusGrade": 79,
            "unitImpactGrade": 82,
            "mainCat1Grade": 94,
            "mainCat2Grade": 93,
            "mainCat3Grade": 86,
            "overallGrade": 88
        },
        {
            "id":59,
            "player": 59,
            "season": 2014,
            "numPlays": 357,
            "numGames": 6,
            "bonusGrade": 80,
            "unitImpactGrade": 84,
            "mainCat1Grade": 87,
            "mainCat2Grade": 93,
            "mainCat3Grade": 90,
            "overallGrade": 88
        },
        {
            "id":15,
            "player": 15,
            "season": 2014,
            "numPlays": 271,
            "numGames": 6,
            "bonusGrade": 76,
            "unitImpactGrade": 81,
            "mainCat1Grade": 93,
            "mainCat2Grade": 90,
            "mainCat3Grade": 93,
            "overallGrade": 88
        },
        {
            "id":78,
            "player": 78,
            "season": 2014,
            "numPlays": 356,
            "numGames": 6,
            "bonusGrade": 85,
            "unitImpactGrade": 86,
            "mainCat1Grade": 85,
            "mainCat2Grade": 94,
            "mainCat3Grade": 87,
            "overallGrade": 88
        },
        {
            "id":38,
            "player": 38,
            "season": 2014,
            "numPlays": 313,
            "numGames": 6,
            "bonusGrade": 79,
            "unitImpactGrade": 69,
            "mainCat1Grade": 90,
            "mainCat2Grade": 89,
            "mainCat3Grade": 92,
            "overallGrade": 88
        },
        {
            "id":75,
            "player": 75,
            "season": 2014,
            "numPlays": 273,
            "numGames": 6,
            "bonusGrade": 77,
            "unitImpactGrade": 90,
            "mainCat1Grade": 96,
            "mainCat2Grade": 90,
            "mainCat3Grade": 91,
            "overallGrade": 88
        },
        {
            "id":95,
            "player": 95,
            "season": 2014,
            "numPlays": 360,
            "numGames": 6,
            "bonusGrade": 90,
            "unitImpactGrade": 96,
            "mainCat1Grade": 92,
            "mainCat2Grade": 86,
            "mainCat3Grade": 84,
            "overallGrade": 88
        },
        {
            "id":74,
            "player": 74,
            "season": 2014,
            "numPlays": 258,
            "numGames": 6,
            "bonusGrade": 78,
            "unitImpactGrade": 80,
            "mainCat1Grade": 90,
            "mainCat2Grade": 92,
            "mainCat3Grade": 89,
            "overallGrade": 88
        },
        {
            "id":73,
            "player": 73,
            "season": 2014,
            "numPlays": 311,
            "numGames": 6,
            "bonusGrade": 82,
            "unitImpactGrade": 70,
            "mainCat1Grade": 89,
            "mainCat2Grade": 92,
            "mainCat3Grade": 89,
            "overallGrade": 88
        },
        {
            "id":3,
            "player": 3,
            "season": 2014,
            "numPlays": 264,
            "numGames": 6,
            "bonusGrade": 81,
            "unitImpactGrade": 83,
            "mainCat1Grade": 89,
            "mainCat2Grade": 87,
            "mainCat3Grade": 92,
            "overallGrade": 88
        },
        {
            "id":30,
            "player": 30,
            "season": 2014,
            "numPlays": 306,
            "numGames": 6,
            "bonusGrade": 82,
            "unitImpactGrade": 77,
            "mainCat1Grade": 90,
            "mainCat2Grade": 90,
            "mainCat3Grade": 91,
            "overallGrade": 88
        },
        {
            "id":90,
            "player": 90,
            "season": 2014,
            "numPlays": 270,
            "numGames": 6,
            "bonusGrade": 66,
            "unitImpactGrade": 85,
            "mainCat1Grade": 97,
            "mainCat2Grade": 94,
            "mainCat3Grade": 96,
            "overallGrade": 88
        },
        {
            "id":70,
            "player": 70,
            "season": 2014,
            "numPlays": 288,
            "numGames": 6,
            "bonusGrade": 79,
            "unitImpactGrade": 85,
            "mainCat1Grade": 88,
            "mainCat2Grade": 92,
            "mainCat3Grade": 91,
            "overallGrade": 88
        },
        {
            "id":53,
            "player": 53,
            "season": 2014,
            "numPlays": 324,
            "numGames": 6,
            "bonusGrade": 85,
            "unitImpactGrade": 76,
            "mainCat1Grade": 87,
            "mainCat2Grade": 89,
            "mainCat3Grade": 89,
            "overallGrade": 88
        },
        {
            "id":87,
            "player": 87,
            "season": 2014,
            "numPlays": 225,
            "numGames": 6,
            "bonusGrade": 81,
            "unitImpactGrade": 87,
            "mainCat1Grade": 88,
            "mainCat2Grade": 94,
            "mainCat3Grade": 87,
            "overallGrade": 88
        },
        {
            "id":99,
            "player": 99,
            "season": 2014,
            "numPlays": 350,
            "numGames": 6,
            "bonusGrade": 81,
            "unitImpactGrade": 81,
            "mainCat1Grade": 94,
            "mainCat2Grade": 89,
            "mainCat3Grade": 89,
            "overallGrade": 88
        },
        {
            "id":8,
            "player": 8,
            "season": 2014,
            "numPlays": 286,
            "numGames": 6,
            "bonusGrade": 81,
            "unitImpactGrade": 86,
            "mainCat1Grade": 89,
            "mainCat2Grade": 87,
            "mainCat3Grade": 94,
            "overallGrade": 88
        },
        {
            "id":34,
            "player": 34,
            "season": 2014,
            "numPlays": 266,
            "numGames": 6,
            "bonusGrade": 80,
            "unitImpactGrade": 76,
            "mainCat1Grade": 87,
            "mainCat2Grade": 95,
            "mainCat3Grade": 91,
            "overallGrade": 88
        },
        {
            "id":1,
            "player": 1,
            "season": 2014,
            "numPlays": 289,
            "numGames": 6,
            "bonusGrade": 83,
            "unitImpactGrade": 76,
            "mainCat1Grade": 89,
            "mainCat2Grade": 92,
            "mainCat3Grade": 88,
            "overallGrade": 88
        },
        {
            "id":31,
            "player": 31,
            "season": 2014,
            "numPlays": 329,
            "numGames": 6,
            "bonusGrade": 79,
            "unitImpactGrade": 91,
            "mainCat1Grade": 91,
            "mainCat2Grade": 89,
            "mainCat3Grade": 90,
            "overallGrade": 87
        },
        {
            "id":48,
            "player": 48,
            "season": 2014,
            "numPlays": 348,
            "numGames": 6,
            "bonusGrade": 81,
            "unitImpactGrade": 82,
            "mainCat1Grade": 92,
            "mainCat2Grade": 91,
            "mainCat3Grade": 85,
            "overallGrade": 87
        },
        {
            "id":62,
            "player": 62,
            "season": 2014,
            "numPlays": 345,
            "numGames": 6,
            "bonusGrade": 81,
            "unitImpactGrade": 77,
            "mainCat1Grade": 91,
            "mainCat2Grade": 88,
            "mainCat3Grade": 90,
            "overallGrade": 87
        },
        {
            "id":83,
            "player": 83,
            "season": 2014,
            "numPlays": 334,
            "numGames": 6,
            "bonusGrade": 78,
            "unitImpactGrade": 87,
            "mainCat1Grade": 88,
            "mainCat2Grade": 92,
            "mainCat3Grade": 90,
            "overallGrade": 87
        },
        {
            "id":76,
            "player": 76,
            "season": 2014,
            "numPlays": 236,
            "numGames": 6,
            "bonusGrade": 76,
            "unitImpactGrade": 85,
            "mainCat1Grade": 90,
            "mainCat2Grade": 92,
            "mainCat3Grade": 88,
            "overallGrade": 87
        },
        {
            "id":20,
            "player": 20,
            "season": 2014,
            "numPlays": 333,
            "numGames": 6,
            "bonusGrade": 72,
            "unitImpactGrade": 80,
            "mainCat1Grade": 90,
            "mainCat2Grade": 89,
            "mainCat3Grade": 96,
            "overallGrade": 87
        },
        {
            "id":29,
            "player": 29,
            "season": 2014,
            "numPlays": 279,
            "numGames": 6,
            "bonusGrade": 81,
            "unitImpactGrade": 89,
            "mainCat1Grade": 87,
            "mainCat2Grade": 89,
            "mainCat3Grade": 89,
            "overallGrade": 87
        },
        {
            "id":44,
            "player": 44,
            "season": 2014,
            "numPlays": 256,
            "numGames": 6,
            "bonusGrade": 79,
            "unitImpactGrade": 94,
            "mainCat1Grade": 89,
            "mainCat2Grade": 91,
            "mainCat3Grade": 89,
            "overallGrade": 87
        },
        {
            "id":33,
            "player": 33,
            "season": 2014,
            "numPlays": 271,
            "numGames": 6,
            "bonusGrade": 71,
            "unitImpactGrade": 80,
            "mainCat1Grade": 93,
            "mainCat2Grade": 92,
            "mainCat3Grade": 90,
            "overallGrade": 87
        },
        {
            "id":100,
            "player": 100,
            "season": 2014,
            "numPlays": 329,
            "numGames": 6,
            "bonusGrade": 77,
            "unitImpactGrade": 80,
            "mainCat1Grade": 88,
            "mainCat2Grade": 91,
            "mainCat3Grade": 90,
            "overallGrade": 87
        },
        {
            "id":86,
            "player": 86,
            "season": 2014,
            "numPlays": 228,
            "numGames": 6,
            "bonusGrade": 80,
            "unitImpactGrade": 84,
            "mainCat1Grade": 88,
            "mainCat2Grade": 94,
            "mainCat3Grade": 87,
            "overallGrade": 87
        },
        {
            "id":85,
            "player": 85,
            "season": 2014,
            "numPlays": 226,
            "numGames": 6,
            "bonusGrade": 81,
            "unitImpactGrade": 96,
            "mainCat1Grade": 90,
            "mainCat2Grade": 89,
            "mainCat3Grade": 89,
            "overallGrade": 87
        },
        {
            "id":84,
            "player": 84,
            "season": 2014,
            "numPlays": 325,
            "numGames": 6,
            "bonusGrade": 82,
            "unitImpactGrade": 82,
            "mainCat1Grade": 89,
            "mainCat2Grade": 90,
            "mainCat3Grade": 89,
            "overallGrade": 87
        },
        {
            "id":6,
            "player": 6,
            "season": 2014,
            "numPlays": 260,
            "numGames": 6,
            "bonusGrade": 78,
            "unitImpactGrade": 79,
            "mainCat1Grade": 93,
            "mainCat2Grade": 88,
            "mainCat3Grade": 89,
            "overallGrade": 87
        },
        {
            "id":60,
            "player": 60,
            "season": 2014,
            "numPlays": 275,
            "numGames": 6,
            "bonusGrade": 76,
            "unitImpactGrade": 91,
            "mainCat1Grade": 91,
            "mainCat2Grade": 85,
            "mainCat3Grade": 92,
            "overallGrade": 86
        },
        {
            "id":63,
            "player": 63,
            "season": 2014,
            "numPlays": 280,
            "numGames": 6,
            "bonusGrade": 83,
            "unitImpactGrade": 75,
            "mainCat1Grade": 87,
            "mainCat2Grade": 89,
            "mainCat3Grade": 85,
            "overallGrade": 86
        },
        {
            "id":25,
            "player": 25,
            "season": 2014,
            "numPlays": 236,
            "numGames": 6,
            "bonusGrade": 74,
            "unitImpactGrade": 82,
            "mainCat1Grade": 86,
            "mainCat2Grade": 92,
            "mainCat3Grade": 90,
            "overallGrade": 86
        },
        {
            "id":13,
            "player": 13,
            "season": 2014,
            "numPlays": 305,
            "numGames": 6,
            "bonusGrade": 79,
            "unitImpactGrade": 82,
            "mainCat1Grade": 88,
            "mainCat2Grade": 90,
            "mainCat3Grade": 87,
            "overallGrade": 86
        },
        {
            "id":47,
            "player": 47,
            "season": 2014,
            "numPlays": 252,
            "numGames": 6,
            "bonusGrade": 74,
            "unitImpactGrade": 76,
            "mainCat1Grade": 88,
            "mainCat2Grade": 92,
            "mainCat3Grade": 88,
            "overallGrade": 85
        },
        {
            "id":56,
            "player": 56,
            "season": 2014,
            "numPlays": 274,
            "numGames": 6,
            "bonusGrade": 75,
            "unitImpactGrade": 86,
            "mainCat1Grade": 86,
            "mainCat2Grade": 90,
            "mainCat3Grade": 88,
            "overallGrade": 85
        },
        {
            "id":43,
            "player": 43,
            "season": 2014,
            "numPlays": 282,
            "numGames": 6,
            "bonusGrade": 77,
            "unitImpactGrade": 74,
            "mainCat1Grade": 86,
            "mainCat2Grade": 87,
            "mainCat3Grade": 89,
            "overallGrade": 85
        },
        {
            "id":17,
            "player": 17,
            "season": 2014,
            "numPlays": 296,
            "numGames": 6,
            "bonusGrade": 79,
            "unitImpactGrade": 85,
            "mainCat1Grade": 85,
            "mainCat2Grade": 90,
            "mainCat3Grade": 80,
            "overallGrade": 84
        }
    ]
});

export default SeasonStat;
