import DS from 'ember-data';

var attr = DS.attr,
    hasMany = DS.hasMany,
    belongsTo = DS.belongsTo;

var SeasonStat = DS.Model.extend({
    player: belongsTo('player',{async:true}),
    season: attr(),
    numPlays: attr(),
    numGames: attr(),
    mainCat1Grade: attr(),
    mainCat2Grade: attr(),
    mainCat3Grade: attr(),
    bonusCatGrade: attr(),
    overallGrade: attr()                   // could be calculated
});

SeasonStat.reopenClass({
FIXTURES:
    [
        {
            "id":1,
            "player": 1,
            "season": 2014,
            "numPlays": 226,
            "numGames": 6,
            "mainCat1Grade": 98,
            "mainCat2Grade": 97,
            "mainCat3Grade": 94,
            "overallGrade": 96
        },
        {
            "id":2,
            "player": 2,
            "season": 2014,
            "numPlays": 203,
            "numGames": 6,
            "mainCat1Grade": 100,
            "mainCat2Grade": 90,
            "mainCat3Grade": 92,
            "overallGrade": 94
        },
        {
            "id":3,
            "player": 3,
            "season": 2014,
            "numPlays": 227,
            "numGames": 6,
            "mainCat1Grade": 88,
            "mainCat2Grade": 91,
            "mainCat3Grade": 92,
            "overallGrade": 90
        },
        {
            "id":4,
            "player": 4,
            "season": 2014,
            "numPlays": 306,
            "numGames": 6,
            "mainCat1Grade": 92,
            "mainCat2Grade": 90,
            "mainCat3Grade": 84,
            "overallGrade": 89
        },
        {
            "id":5,
            "player": 5,
            "season": 2014,
            "numPlays": 299,
            "numGames": 6,
            "mainCat1Grade": 71,
            "mainCat2Grade": 78,
            "mainCat3Grade": 74,
            "overallGrade": 74
        },
        {
            "id":6,
            "player": 6,
            "season": 2014,
            "numPlays": 326,
            "numGames": 6,
            "mainCat1Grade": 94,
            "mainCat2Grade": 97,
            "mainCat3Grade": 98,
            "overallGrade": 97
        },
        {
            "id":7,
            "player": 7,
            "season": 2014,
            "numPlays": 340,
            "numGames": 6,
            "mainCat1Grade": 99,
            "mainCat2Grade": 96,
            "mainCat3Grade": 97,
            "overallGrade": 98
        },
        {
            "id":8,
            "player": 8,
            "season": 2014,
            "numPlays": 323,
            "numGames": 6,
            "mainCat1Grade": 91,
            "mainCat2Grade": 94,
            "mainCat3Grade": 96,
            "overallGrade": 94
        },
        {
            "id":9,
            "player": 9,
            "season": 2014,
            "numPlays": 217,
            "numGames": 6,
            "mainCat1Grade": 91,
            "mainCat2Grade": 92,
            "mainCat3Grade": 96,
            "overallGrade": 93
        },
        {
            "id":10,
            "player": 10,
            "season": 2014,
            "numPlays": 256,
            "numGames": 6,
            "mainCat1Grade": 92,
            "mainCat2Grade": 99,
            "mainCat3Grade": 95,
            "overallGrade": 95
        },
        {
            "id":11,
            "player": 11,
            "season": 2014,
            "numPlays": 369,
            "numGames": 6,
            "mainCat1Grade": 95,
            "mainCat2Grade": 94,
            "mainCat3Grade": 90,
            "overallGrade": 93
        },
        {
            "id":12,
            "player": 12,
            "season": 2014,
            "numPlays": 358,
            "numGames": 6,
            "mainCat1Grade": 93,
            "mainCat2Grade": 92,
            "mainCat3Grade": 95,
            "overallGrade": 93
        },
        {
            "id":13,
            "player": 13,
            "season": 2014,
            "numPlays": 294,
            "numGames": 6,
            "mainCat1Grade": 90,
            "mainCat2Grade": 92,
            "mainCat3Grade": 90,
            "overallGrade": 91
        },
        {
            "id":14,
            "player": 14,
            "season": 2014,
            "numPlays": 346,
            "numGames": 6,
            "mainCat1Grade": 96,
            "mainCat2Grade": 97,
            "mainCat3Grade": 89,
            "overallGrade": 94
        },
        {
            "id":15,
            "player": 15,
            "season": 2014,
            "numPlays": 326,
            "numGames": 6,
            "mainCat1Grade": 95,
            "mainCat2Grade": 94,
            "mainCat3Grade": 95,
            "overallGrade": 94
        },
        {
            "id":16,
            "player": 16,
            "season": 2014,
            "numPlays": 332,
            "numGames": 6,
            "mainCat1Grade": 100,
            "mainCat2Grade": 96,
            "mainCat3Grade": 100,
            "overallGrade": 99
        },
        {
            "id":17,
            "player": 17,
            "season": 2014,
            "numPlays": 284,
            "numGames": 6,
            "mainCat1Grade": 87,
            "mainCat2Grade": 87,
            "mainCat3Grade": 90,
            "overallGrade": 88
        },
        {
            "id":18,
            "player": 18,
            "season": 2014,
            "numPlays": 355,
            "numGames": 6,
            "mainCat1Grade": 91,
            "mainCat2Grade": 92,
            "mainCat3Grade": 102,
            "overallGrade": 95
        },
        {
            "id":19,
            "player": 19,
            "season": 2014,
            "numPlays": 268,
            "numGames": 6,
            "mainCat1Grade": 96,
            "mainCat2Grade": 92,
            "mainCat3Grade": 91,
            "overallGrade": 93
        },
        {
            "id":20,
            "player": 20,
            "season": 2014,
            "numPlays": 393,
            "numGames": 6,
            "mainCat1Grade": 88,
            "mainCat2Grade": 96,
            "mainCat3Grade": 93,
            "overallGrade": 93
        },
        {
            "id":21,
            "player": 21,
            "season": 2014,
            "numPlays": 352,
            "numGames": 6,
            "mainCat1Grade": 94,
            "mainCat2Grade": 93,
            "mainCat3Grade": 97,
            "overallGrade": 95
        },
        {
            "id":22,
            "player": 22,
            "season": 2014,
            "numPlays": 305,
            "numGames": 6,
            "mainCat1Grade": 94,
            "mainCat2Grade": 92,
            "mainCat3Grade": 94,
            "overallGrade": 93
        },
        {
            "id":23,
            "player": 23,
            "season": 2014,
            "numPlays": 312,
            "numGames": 6,
            "mainCat1Grade": 93,
            "mainCat2Grade": 87,
            "mainCat3Grade": 93,
            "overallGrade": 91
        },
        {
            "id":24,
            "player": 24,
            "season": 2014,
            "numPlays": 335,
            "numGames": 6,
            "mainCat1Grade": 91,
            "mainCat2Grade": 85,
            "mainCat3Grade": 92,
            "overallGrade": 89
        },
        {
            "id":25,
            "player": 25,
            "season": 2014,
            "numPlays": 303,
            "numGames": 6,
            "mainCat1Grade": 92,
            "mainCat2Grade": 94,
            "mainCat3Grade": 98,
            "overallGrade": 95
        },
        {
            "id":26,
            "player": 26,
            "season": 2014,
            "numPlays": 241,
            "numGames": 6,
            "mainCat1Grade": 95,
            "mainCat2Grade": 97,
            "mainCat3Grade": 92,
            "overallGrade": 94
        },
        {
            "id":27,
            "player": 27,
            "season": 2014,
            "numPlays": 299,
            "numGames": 6,
            "mainCat1Grade": 94,
            "mainCat2Grade": 93,
            "mainCat3Grade": 98,
            "overallGrade": 95
        },
        {
            "id":28,
            "player": 28,
            "season": 2014,
            "numPlays": 317,
            "numGames": 6,
            "mainCat1Grade": 88,
            "mainCat2Grade": 97,
            "mainCat3Grade": 90,
            "overallGrade": 92
        },
        {
            "id":29,
            "player": 29,
            "season": 2014,
            "numPlays": 242,
            "numGames": 6,
            "mainCat1Grade": 95,
            "mainCat2Grade": 90,
            "mainCat3Grade": 93,
            "overallGrade": 93
        },
        {
            "id":30,
            "player": 30,
            "season": 2014,
            "numPlays": 330,
            "numGames": 6,
            "mainCat1Grade": 93,
            "mainCat2Grade": 90,
            "mainCat3Grade": 95,
            "overallGrade": 93
        },
        {
            "id":31,
            "player": 31,
            "season": 2014,
            "numPlays": 286,
            "numGames": 6,
            "mainCat1Grade": 96,
            "mainCat2Grade": 89,
            "mainCat3Grade": 97,
            "overallGrade": 94
        },
        {
            "id":32,
            "player": 32,
            "season": 2014,
            "numPlays": 322,
            "numGames": 6,
            "mainCat1Grade": 95,
            "mainCat2Grade": 87,
            "mainCat3Grade": 95,
            "overallGrade": 92
        },
        {
            "id":33,
            "player": 33,
            "season": 2014,
            "numPlays": 238,
            "numGames": 6,
            "mainCat1Grade": 93,
            "mainCat2Grade": 97,
            "mainCat3Grade": 89,
            "overallGrade": 93
        },
        {
            "id":34,
            "player": 34,
            "season": 2014,
            "numPlays": 315,
            "numGames": 6,
            "mainCat1Grade": 95,
            "mainCat2Grade": 88,
            "mainCat3Grade": 95,
            "overallGrade": 93
        },
        {
            "id":35,
            "player": 35,
            "season": 2014,
            "numPlays": 370,
            "numGames": 6,
            "mainCat1Grade": 92,
            "mainCat2Grade": 90,
            "mainCat3Grade": 94,
            "overallGrade": 92
        },
        {
            "id":36,
            "player": 36,
            "season": 2014,
            "numPlays": 285,
            "numGames": 6,
            "mainCat1Grade": 94,
            "mainCat2Grade": 95,
            "mainCat3Grade": 87,
            "overallGrade": 92
        },
        {
            "id":37,
            "player": 37,
            "season": 2014,
            "numPlays": 322,
            "numGames": 6,
            "mainCat1Grade": 90,
            "mainCat2Grade": 93,
            "mainCat3Grade": 90,
            "overallGrade": 91
        },
        {
            "id":38,
            "player": 38,
            "season": 2014,
            "numPlays": 296,
            "numGames": 6,
            "mainCat1Grade": 92,
            "mainCat2Grade": 92,
            "mainCat3Grade": 96,
            "overallGrade": 93
        },
        {
            "id":39,
            "player": 39,
            "season": 2014,
            "numPlays": 318,
            "numGames": 6,
            "mainCat1Grade": 91,
            "mainCat2Grade": 96,
            "mainCat3Grade": 98,
            "overallGrade": 95
        },
        {
            "id":40,
            "player": 40,
            "season": 2014,
            "numPlays": 250,
            "numGames": 6,
            "mainCat1Grade": 96,
            "mainCat2Grade": 92,
            "mainCat3Grade": 94,
            "overallGrade": 94
        },
        {
            "id":41,
            "player": 41,
            "season": 2014,
            "numPlays": 354,
            "numGames": 6,
            "mainCat1Grade": 88,
            "mainCat2Grade": 93,
            "mainCat3Grade": 94,
            "overallGrade": 92
        },
        {
            "id":42,
            "player": 42,
            "season": 2014,
            "numPlays": 324,
            "numGames": 6,
            "mainCat1Grade": 94,
            "mainCat2Grade": 93,
            "mainCat3Grade": 97,
            "overallGrade": 95
        },
        {
            "id":43,
            "player": 43,
            "season": 2014,
            "numPlays": 308,
            "numGames": 6,
            "mainCat1Grade": 93,
            "mainCat2Grade": 93,
            "mainCat3Grade": 88,
            "overallGrade": 92
        },
        {
            "id":44,
            "player": 44,
            "season": 2014,
            "numPlays": 331,
            "numGames": 6,
            "mainCat1Grade": 93,
            "mainCat2Grade": 97,
            "mainCat3Grade": 95,
            "overallGrade": 95
        },
        {
            "id":45,
            "player": 45,
            "season": 2014,
            "numPlays": 352,
            "numGames": 6,
            "mainCat1Grade": 94,
            "mainCat2Grade": 91,
            "mainCat3Grade": 92,
            "overallGrade": 92
        },
        {
            "id":46,
            "player": 46,
            "season": 2014,
            "numPlays": 358,
            "numGames": 6,
            "mainCat1Grade": 90,
            "mainCat2Grade": 89,
            "mainCat3Grade": 99,
            "overallGrade": 93
        },
        {
            "id":47,
            "player": 47,
            "season": 2014,
            "numPlays": 282,
            "numGames": 6,
            "mainCat1Grade": 100,
            "mainCat2Grade": 92,
            "mainCat3Grade": 94,
            "overallGrade": 95
        },
        {
            "id":48,
            "player": 48,
            "season": 2014,
            "numPlays": 308,
            "numGames": 6,
            "mainCat1Grade": 97,
            "mainCat2Grade": 90,
            "mainCat3Grade": 93,
            "overallGrade": 93
        },
        {
            "id":49,
            "player": 49,
            "season": 2014,
            "numPlays": 286,
            "numGames": 6,
            "mainCat1Grade": 94,
            "mainCat2Grade": 90,
            "mainCat3Grade": 93,
            "overallGrade": 92
        },
        {
            "id":50,
            "player": 50,
            "season": 2014,
            "numPlays": 317,
            "numGames": 6,
            "mainCat1Grade": 96,
            "mainCat2Grade": 98,
            "mainCat3Grade": 89,
            "overallGrade": 94
        },
        {
            "id":51,
            "player": 51,
            "season": 2014,
            "numPlays": 325,
            "numGames": 6,
            "mainCat1Grade": 94,
            "mainCat2Grade": 88,
            "mainCat3Grade": 89,
            "overallGrade": 90
        },
        {
            "id":52,
            "player": 52,
            "season": 2014,
            "numPlays": 301,
            "numGames": 6,
            "mainCat1Grade": 92,
            "mainCat2Grade": 96,
            "mainCat3Grade": 91,
            "overallGrade": 93
        },
        {
            "id":53,
            "player": 53,
            "season": 2014,
            "numPlays": 259,
            "numGames": 6,
            "mainCat1Grade": 93,
            "mainCat2Grade": 91,
            "mainCat3Grade": 94,
            "overallGrade": 92
        },
        {
            "id":54,
            "player": 54,
            "season": 2014,
            "numPlays": 294,
            "numGames": 6,
            "mainCat1Grade": 96,
            "mainCat2Grade": 102,
            "mainCat3Grade": 91,
            "overallGrade": 96
        },
        {
            "id":55,
            "player": 55,
            "season": 2014,
            "numPlays": 319,
            "numGames": 6,
            "mainCat1Grade": 96,
            "mainCat2Grade": 95,
            "mainCat3Grade": 91,
            "overallGrade": 94
        },
        {
            "id":56,
            "player": 56,
            "season": 2014,
            "numPlays": 239,
            "numGames": 6,
            "mainCat1Grade": 88,
            "mainCat2Grade": 97,
            "mainCat3Grade": 92,
            "overallGrade": 92
        },
        {
            "id":57,
            "player": 57,
            "season": 2014,
            "numPlays": 296,
            "numGames": 6,
            "mainCat1Grade": 98,
            "mainCat2Grade": 90,
            "mainCat3Grade": 93,
            "overallGrade": 93
        },
        {
            "id":58,
            "player": 58,
            "season": 2014,
            "numPlays": 247,
            "numGames": 6,
            "mainCat1Grade": 94,
            "mainCat2Grade": 94,
            "mainCat3Grade": 95,
            "overallGrade": 94
        },
        {
            "id":59,
            "player": 59,
            "season": 2014,
            "numPlays": 257,
            "numGames": 6,
            "mainCat1Grade": 93,
            "mainCat2Grade": 94,
            "mainCat3Grade": 92,
            "overallGrade": 93
        },
        {
            "id":60,
            "player": 60,
            "season": 2014,
            "numPlays": 263,
            "numGames": 6,
            "mainCat1Grade": 99,
            "mainCat2Grade": 92,
            "mainCat3Grade": 96,
            "overallGrade": 96
        },
        {
            "id":61,
            "player": 61,
            "season": 2014,
            "numPlays": 327,
            "numGames": 6,
            "mainCat1Grade": 95,
            "mainCat2Grade": 94,
            "mainCat3Grade": 92,
            "overallGrade": 94
        },
        {
            "id":62,
            "player": 62,
            "season": 2014,
            "numPlays": 338,
            "numGames": 6,
            "mainCat1Grade": 91,
            "mainCat2Grade": 94,
            "mainCat3Grade": 90,
            "overallGrade": 92
        },
        {
            "id":63,
            "player": 63,
            "season": 2014,
            "numPlays": 296,
            "numGames": 6,
            "mainCat1Grade": 86,
            "mainCat2Grade": 94,
            "mainCat3Grade": 89,
            "overallGrade": 90
        },
        {
            "id":64,
            "player": 64,
            "season": 2014,
            "numPlays": 234,
            "numGames": 6,
            "mainCat1Grade": 94,
            "mainCat2Grade": 95,
            "mainCat3Grade": 93,
            "overallGrade": 94
        },
        {
            "id":65,
            "player": 65,
            "season": 2014,
            "numPlays": 366,
            "numGames": 6,
            "mainCat1Grade": 97,
            "mainCat2Grade": 97,
            "mainCat3Grade": 95,
            "overallGrade": 96
        },
        {
            "id":66,
            "player": 66,
            "season": 2014,
            "numPlays": 316,
            "numGames": 6,
            "mainCat1Grade": 95,
            "mainCat2Grade": 95,
            "mainCat3Grade": 88,
            "overallGrade": 93
        },
        {
            "id":67,
            "player": 67,
            "season": 2014,
            "numPlays": 316,
            "numGames": 6,
            "mainCat1Grade": 97,
            "mainCat2Grade": 94,
            "mainCat3Grade": 97,
            "overallGrade": 95
        },
        {
            "id":68,
            "player": 68,
            "season": 2014,
            "numPlays": 340,
            "numGames": 6,
            "mainCat1Grade": 88,
            "mainCat2Grade": 98,
            "mainCat3Grade": 92,
            "overallGrade": 93
        },
        {
            "id":69,
            "player": 69,
            "season": 2014,
            "numPlays": 306,
            "numGames": 6,
            "mainCat1Grade": 87,
            "mainCat2Grade": 90,
            "mainCat3Grade": 97,
            "overallGrade": 91
        },
        {
            "id":70,
            "player": 70,
            "season": 2014,
            "numPlays": 247,
            "numGames": 6,
            "mainCat1Grade": 91,
            "mainCat2Grade": 90,
            "mainCat3Grade": 101,
            "overallGrade": 94
        },
        {
            "id":71,
            "player": 71,
            "season": 2014,
            "numPlays": 328,
            "numGames": 6,
            "mainCat1Grade": 89,
            "mainCat2Grade": 91,
            "mainCat3Grade": 93,
            "overallGrade": 91
        },
        {
            "id":72,
            "player": 72,
            "season": 2014,
            "numPlays": 289,
            "numGames": 6,
            "mainCat1Grade": 90,
            "mainCat2Grade": 93,
            "mainCat3Grade": 95,
            "overallGrade": 93
        },
        {
            "id":73,
            "player": 73,
            "season": 2014,
            "numPlays": 332,
            "numGames": 6,
            "mainCat1Grade": 95,
            "mainCat2Grade": 90,
            "mainCat3Grade": 95,
            "overallGrade": 94
        },
        {
            "id":74,
            "player": 74,
            "season": 2014,
            "numPlays": 346,
            "numGames": 6,
            "mainCat1Grade": 91,
            "mainCat2Grade": 93,
            "mainCat3Grade": 94,
            "overallGrade": 92
        },
        {
            "id":75,
            "player": 75,
            "season": 2014,
            "numPlays": 215,
            "numGames": 6,
            "mainCat1Grade": 93,
            "mainCat2Grade": 87,
            "mainCat3Grade": 96,
            "overallGrade": 92
        },
        {
            "id":76,
            "player": 76,
            "season": 2014,
            "numPlays": 263,
            "numGames": 6,
            "mainCat1Grade": 94,
            "mainCat2Grade": 97,
            "mainCat3Grade": 88,
            "overallGrade": 93
        },
        {
            "id":77,
            "player": 77,
            "season": 2014,
            "numPlays": 301,
            "numGames": 6,
            "mainCat1Grade": 95,
            "mainCat2Grade": 88,
            "mainCat3Grade": 93,
            "overallGrade": 92
        },
        {
            "id":78,
            "player": 78,
            "season": 2014,
            "numPlays": 251,
            "numGames": 6,
            "mainCat1Grade": 92,
            "mainCat2Grade": 93,
            "mainCat3Grade": 94,
            "overallGrade": 93
        },
        {
            "id":79,
            "player": 79,
            "season": 2014,
            "numPlays": 330,
            "numGames": 6,
            "mainCat1Grade": 91,
            "mainCat2Grade": 95,
            "mainCat3Grade": 96,
            "overallGrade": 94
        },
        {
            "id":80,
            "player": 80,
            "season": 2014,
            "numPlays": 262,
            "numGames": 6,
            "mainCat1Grade": 95,
            "mainCat2Grade": 94,
            "mainCat3Grade": 90,
            "overallGrade": 93
        },
        {
            "id":81,
            "player": 81,
            "season": 2014,
            "numPlays": 305,
            "numGames": 6,
            "mainCat1Grade": 89,
            "mainCat2Grade": 90,
            "mainCat3Grade": 90,
            "overallGrade": 89
        },
        {
            "id":82,
            "player": 82,
            "season": 2014,
            "numPlays": 377,
            "numGames": 6,
            "mainCat1Grade": 91,
            "mainCat2Grade": 92,
            "mainCat3Grade": 92,
            "overallGrade": 92
        },
        {
            "id":83,
            "player": 83,
            "season": 2014,
            "numPlays": 210,
            "numGames": 6,
            "mainCat1Grade": 94,
            "mainCat2Grade": 95,
            "mainCat3Grade": 88,
            "overallGrade": 92
        },
        {
            "id":84,
            "player": 84,
            "season": 2014,
            "numPlays": 263,
            "numGames": 6,
            "mainCat1Grade": 98,
            "mainCat2Grade": 92,
            "mainCat3Grade": 91,
            "overallGrade": 94
        },
        {
            "id":85,
            "player": 85,
            "season": 2014,
            "numPlays": 334,
            "numGames": 6,
            "mainCat1Grade": 91,
            "mainCat2Grade": 91,
            "mainCat3Grade": 97,
            "overallGrade": 93
        },
        {
            "id":86,
            "player": 86,
            "season": 2014,
            "numPlays": 382,
            "numGames": 6,
            "mainCat1Grade": 89,
            "mainCat2Grade": 92,
            "mainCat3Grade": 94,
            "overallGrade": 92
        },
        {
            "id":87,
            "player": 87,
            "season": 2014,
            "numPlays": 258,
            "numGames": 6,
            "mainCat1Grade": 95,
            "mainCat2Grade": 96,
            "mainCat3Grade": 93,
            "overallGrade": 95
        },
        {
            "id":88,
            "player": 88,
            "season": 2014,
            "numPlays": 315,
            "numGames": 6,
            "mainCat1Grade": 96,
            "mainCat2Grade": 89,
            "mainCat3Grade": 89,
            "overallGrade": 92
        },
        {
            "id":89,
            "player": 89,
            "season": 2014,
            "numPlays": 273,
            "numGames": 6,
            "mainCat1Grade": 95,
            "mainCat2Grade": 91,
            "mainCat3Grade": 95,
            "overallGrade": 94
        },
        {
            "id":90,
            "player": 90,
            "season": 2014,
            "numPlays": 373,
            "numGames": 6,
            "mainCat1Grade": 99,
            "mainCat2Grade": 94,
            "mainCat3Grade": 91,
            "overallGrade": 94
        },
        {
            "id":91,
            "player": 91,
            "season": 2014,
            "numPlays": 293,
            "numGames": 6,
            "mainCat1Grade": 91,
            "mainCat2Grade": 89,
            "mainCat3Grade": 89,
            "overallGrade": 90
        },
        {
            "id":92,
            "player": 92,
            "season": 2014,
            "numPlays": 328,
            "numGames": 6,
            "mainCat1Grade": 90,
            "mainCat2Grade": 101,
            "mainCat3Grade": 87,
            "overallGrade": 93
        },
        {
            "id":93,
            "player": 93,
            "season": 2014,
            "numPlays": 385,
            "numGames": 6,
            "mainCat1Grade": 97,
            "mainCat2Grade": 93,
            "mainCat3Grade": 90,
            "overallGrade": 93
        },
        {
            "id":94,
            "player": 94,
            "season": 2014,
            "numPlays": 297,
            "numGames": 6,
            "mainCat1Grade": 96,
            "mainCat2Grade": 97,
            "mainCat3Grade": 89,
            "overallGrade": 94
        },
        {
            "id":95,
            "player": 95,
            "season": 2014,
            "numPlays": 357,
            "numGames": 6,
            "mainCat1Grade": 89,
            "mainCat2Grade": 92,
            "mainCat3Grade": 90,
            "overallGrade": 91
        },
        {
            "id":96,
            "player": 96,
            "season": 2014,
            "numPlays": 367,
            "numGames": 6,
            "mainCat1Grade": 95,
            "mainCat2Grade": 88,
            "mainCat3Grade": 89,
            "overallGrade": 91
        },
        {
            "id":97,
            "player": 97,
            "season": 2014,
            "numPlays": 285,
            "numGames": 6,
            "mainCat1Grade": 90,
            "mainCat2Grade": 94,
            "mainCat3Grade": 91,
            "overallGrade": 92
        },
        {
            "id":98,
            "player": 98,
            "season": 2014,
            "numPlays": 340,
            "numGames": 6,
            "mainCat1Grade": 95,
            "mainCat2Grade": 93,
            "mainCat3Grade": 92,
            "overallGrade": 93
        },
        {
            "id":99,
            "player": 99,
            "season": 2014,
            "numPlays": 353,
            "numGames": 6,
            "mainCat1Grade": 94,
            "mainCat2Grade": 92,
            "mainCat3Grade": 90,
            "overallGrade": 92
        },
        {
            "id":100,
            "player": 100,
            "season": 2014,
            "numPlays": 315,
            "numGames": 6,
            "mainCat1Grade": 94,
            "mainCat2Grade": 94,
            "mainCat3Grade": 93,
            "overallGrade": 94
        }
    ]
});

export default SeasonStat;
